const conf = {
    DATA_SOURCE_KEY : import.meta.env.VITE_DATA_SOURCE_KEY,

    // MAIL_LIST FULL URL
    FRONTEND_MAIL_SUBMIT_URL: import.meta.env.VITE_FRONTEND_MAIL_SUBMIT_URL,

     // LIFE BLOG FULL URLs
    FRONTEND_LIFE_BLOG_HOME_URL: import.meta.env.VITE_FRONTEND_LIFE_BLOG_HOME_URL,
    FRONTEND_LIFE_BLOG_URL: import.meta.env.VITE_FRONTEND_LIFE_BLOG_URL,
    FRONTEND_LIFE_BLOG_SEARCH_URL: import.meta.env.VITE_FRONTEND_LIFE_BLOG_SEARCH_URL,
    FRONTEND_LIFE_BLOG_COUNT_URL: import.meta.env.VITE_FRONTEND_LIFE_BLOG_COUNT_URL,
    FRONTEND_LIFE_BLOG_TOPICS_URL: import.meta.env.VITE_FRONTEND_LIFE_BLOG_TOPICS_URL,

    // TECH BLOG FULL URLs
    FRONTEND_TECH_BLOG_HOME_URL: import.meta.env.VITE_FRONTEND_TECH_BLOG_HOME_URL,
    FRONTEND_TECH_BLOG_URL: import.meta.env.VITE_FRONTEND_TECH_BLOG_URL,
    FRONTEND_TECH_BLOG_SEARCH_URL: import.meta.env.VITE_FRONTEND_TECH_BLOG_SEARCH_URL,
    FRONTEND_TECH_BLOG_COUNT_URL: import.meta.env.VITE_FRONTEND_TECH_BLOG_COUNT_URL,
    FRONTEND_TECH_BLOG_TOPICS_URL: import.meta.env.VITE_FRONTEND_TECH_BLOG_TOPICS_URL,

    // ADMIN FULL URLs
    FRONTEND_ADMIN_REGISTER_URL: import.meta.env.VITE_FRONTEND_ADMIN_REGISTER_URL,
    FRONTEND_ADMIN_VERIFY_TOKEN_URL: import.meta.env.VITE_FRONTEND_ADMIN_VERIFY_TOKEN_URL,
    FRONTEND_ADMIN_LOGIN_URL: import.meta.env.VITE_FRONTEND_ADMIN_LOGIN_URL,
    FRONTEND_ADMIN_CREATE_BLOG_URL: import.meta.env.VITE_FRONTEND_ADMIN_CREATE_BLOG_URL,
    FRONTEND_ADMIN_GET_BLOG_URL: import.meta.env.VITE_FRONTEND_ADMIN_GET_BLOG_URL,
    FRONTEND_ADMIN_UPDATE_BLOG_URL: import.meta.env.VITE_FRONTEND_ADMIN_UPDATE_BLOG_URL,
    FRONTEND_ADMIN_DELETE_BLOG_URL: import.meta.env.VITE_FRONTEND_ADMIN_DELETE_BLOG_URL,
    FRONTEND_ADMIN_SEARCH_BLOGS_URL: import.meta.env.VITE_FRONTEND_ADMIN_SEARCH_BLOGS_URL,
    FRONTEND_ADMIN_GET_BLOG_BY_ID_URL: import.meta.env.VITE_FRONTEND_ADMIN_GET_BLOG_BY_ID_URL,
    FRONTEND_ADMIN_GET_MESSAGE_PREVIEW_URL: import.meta.env.VITE_FRONTEND_ADMIN_GET_MESSAGE_PREVIEW_URL,
    FRONTEND_ADMIN_GET_MESSAGE_URL: import.meta.env.VITE_FRONTEND_ADMIN_GET_MESSAGE_URL,
    FRONTEND_ADMIN_MESSAGE_COUNT_URL: import.meta.env.VITE_FRONTEND_ADMIN_MESSAGE_COUNT_URL,
    FRONTEND_ADMIN_DELETE_MESSAGE_URL: import.meta.env.VITE_FRONTEND_ADMIN_DELETE_MESSAGE_URL,
    FRONTEND_ADMIN_MARK_MESSAGE_AS_READ_URL: import.meta.env.VITE_FRONTEND_ADMIN_MARK_MESSAGE_AS_READ_URL,
    FRONTEND_ADMIN_LOGOUT_URL: import.meta.env.VITE_FRONTEND_ADMIN_LOGOUT_URL,

    // MESSAGES FULL URL
    FRONTEND_MESSAGE_SUBMIT_URL: import.meta.env.VITE_FRONTEND_MESSAGE_SUBMIT_URL,
}

export default conf;